### ISSUE TITLE
No way to read the comments?

### ISSUE THREAD

**Issue by pushkargaikwad** [mattrighetti/HNReaderApp#2]
Is there any way to see comments or that feature hasn't been built? as right now whichever text you click, it only opens the article link, not the HN discussion.

**Comment by mattrighetti** [comment]
That is in my future work, unfortunately at the moment the application does just that

**Comment by mattrighetti** [comment]
Released a [beta](https://github.com/mattrighetti/HNReaderApp/releases/tag/v1.1.0-beta1) for this that will be officially released as soon as it reaches a good stability level
